add documentation for data feed API
ceramicnetwork/docs-docusaurus pull request #91
Opened 2024-05-16 16:02 UTC by JustinaPetr

Add documentation for the Data Feed API to developers.ceramic.network

2024-05-16 16:16 UTC, JustinaPetr commented
Hey @ukstv Here's the first commit to add the documentation for the Data Feed API. One question that I added to the notion too - do we have a list of endpoints for the API somewhere?

2024-05-21 13:16 UTC, ukstv commented on docs/protocol/js-ceramic/networking/data-feed-api.md
> +To understnad Data Feed API, it's important to have a basic understanding of Server-Sent Events (SSE) and the EventSource interface.
```suggestion
To understand Data Feed API, it's important to have a basic understanding of [Server-Sent Events (SSE)](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events) and the [EventSource](https://developer.mozilla.org/en-US/docs/Web/API/EventSource) interface.
```

2024-05-21 13:17 UTC, ukstv requested changes
Typo, and pls add links to MDN for SSE and EventSource.

2024-05-21 16:04 UTC, ukstv approved these changes

2024-05-22 15:23 UTC, merged